# Generated by Django 5.2.7 on 2026-02-12 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Stored for record keeping even if user is deleted",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ACCESS", "Access"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., Organization, Project, Task",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("query_params", models.JSONField(blank=True, null=True)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(db_index=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional context-specific data",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "user"],
                        name="core_activi_timesta_05b791_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_activi_resourc_bfb71b_idx",
                    ),
                    models.Index(
                        fields=["action", "status_code"],
                        name="core_activi_action_66182e_idx",
                    ),
                ],
            },
        ),
    ]
