# Generated by Django 5.2.8 on 2026-01-27 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_is_self_remove_allowed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], default='TO_DO', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 1), ('MEDIUM', 2), ('HIGH', 3), ('URGENT', 4)], default='MEDIUM', max_length=50)),
                ('task_type', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement'), ('DOCUMENTATION', 'Documentation')], default='FEATURE', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
