# Generated by Django 5.2.7 on 2026-02-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allow_member_invites", models.BooleanField(default=False)),
                ("allow_member_updates", models.BooleanField(default=False)),
                ("allow_member_removal", models.BooleanField(default=False)),
                ("allow_self_removal", models.BooleanField(default=False)),
                ("require_approval_for_invites", models.BooleanField(default=False)),
                ("require_approval_for_updates", models.BooleanField(default=False)),
                ("require_approval_for_removal", models.BooleanField(default=False)),
                ("max_members", models.PositiveIntegerField(default=50)),
                ("max_teams", models.PositiveIntegerField(default=5)),
                ("max_projects", models.PositiveIntegerField(default=10)),
                (
                    "default_member_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "invite_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                (
                    "update_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                (
                    "remove_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                (
                    "create_team_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                (
                    "create_project_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                ("allow_team_creation", models.BooleanField(default=False)),
                ("allow_project_creation", models.BooleanField(default=False)),
                ("require_approval_for_team", models.BooleanField(default=False)),
                ("require_approval_for_project", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allow_member_invites", models.BooleanField(default=False)),
                ("allow_member_updates", models.BooleanField(default=False)),
                ("allow_member_removal", models.BooleanField(default=False)),
                ("allow_self_removal", models.BooleanField(default=False)),
                ("require_approval_for_invites", models.BooleanField(default=False)),
                ("require_approval_for_updates", models.BooleanField(default=False)),
                ("require_approval_for_removal", models.BooleanField(default=False)),
                ("allow_task_creation", models.BooleanField(default=True)),
                ("allow_task_updates", models.BooleanField(default=True)),
                ("allow_task_deletions", models.BooleanField(default=True)),
                ("only_assignee_can_update_task", models.BooleanField(default=False)),
                (
                    "create_task_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "update_task_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "delete_task_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                ("max_members", models.PositiveIntegerField(default=20)),
                (
                    "default_member_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "invite_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "update_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "remove_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                ("inherit_base_rules_from_team", models.BooleanField(default=False)),
                ("inherit_base_rules_from_org", models.BooleanField(default=False)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allow_member_invites", models.BooleanField(default=False)),
                ("allow_member_updates", models.BooleanField(default=False)),
                ("allow_member_removal", models.BooleanField(default=False)),
                ("allow_self_removal", models.BooleanField(default=False)),
                ("require_approval_for_invites", models.BooleanField(default=False)),
                ("require_approval_for_updates", models.BooleanField(default=False)),
                ("require_approval_for_removal", models.BooleanField(default=False)),
                ("max_members", models.PositiveIntegerField(default=20)),
                ("max_projects", models.PositiveIntegerField(default=10)),
                (
                    "default_member_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "invite_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "update_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "remove_member_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                (
                    "create_project_min_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Lead"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MANAGER",
                        max_length=20,
                    ),
                ),
                ("allow_project_creation", models.BooleanField(default=False)),
                ("require_approval_for_project", models.BooleanField(default=False)),
                ("inherit_base_rules_from_org", models.BooleanField(default=False)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
