# Generated by Django 5.2.7 on 2025-11-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_self_remove_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
